# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: local
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  dependsOn: Build
  condition: false
  jobs:
    - deployment: DeployToTest
      environment: Test
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "Deploying to test..."

- stage: Production
  dependsOn: Build
  condition: false
  jobs:
    - deployment: DeployToTest
      environment: Production
      strategy:
        runOnce:
          deploy:
            steps:
              - script: echo "Deploying to test..."