# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: local
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: DeployTest
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
  jobs:
    - job: DeployToTest
      steps:
        - script: |
            echo "Deploying to test container app"
          displayName: 'Deploy to test'

- stage: DeployProd
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  jobs:
    - job: DeployToProd
      steps:
        - script: |
            echo "Deploying to prod container app"
          displayName: 'Deploy to prod'