# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      name: local
    steps:
    - task: Docker@2
      inputs:
        repository: 'sigil-api'
        containerRegistry: 'SIGIL-PS ACR'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: Deploy Test
  jobs:
  - job: DeployContainerApp
    displayName: Deploy Container App
    pool:
      name: local
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure for Students Subscription'
        KeyVaultName: 'reshapelab-sigil-ps'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Azure for Students Subscription'
        acrName: 'reshapelab'
        acrUsername: 'reshapelab'
        acrPassword: '$(ACR-Password)'
        imageToDeploy: 'reshapelab.azurecr.io/sigil-api:$(tag)'
        containerAppName: 'sigil-api-test'
        resourceGroup: 'reshapelab'
        containerAppEnvironment: 'Test'
        targetPort: '80'
        environmentVariables: 'OPENAI_API_KEY=$(OpenAI-API-Key) MYSQL_HOST=$(MySQL-Host) MYSQL_DATABASE=$(MySQL-DBName-Test) MYSQL_USER=$(MySQL-User) MYSQL_PASSWORD=$(MySQL-Password)'

- stage: Production
  displayName: Deploy Production
  jobs:
  - job: DeployContainerApp
    displayName: Deploy Container App
    pool:
      name: local
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure for Students Subscription'
        KeyVaultName: 'reshapelab-sigil-ps'
        SecretsFilter: '*'
        RunAsPreJob: true
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Azure for Students Subscription'
        acrName: 'reshapelab'
        acrUsername: 'reshapelab'
        acrPassword: '$(ACR-Password)'
        imageToDeploy: 'reshapelab.azurecr.io/sigil-api:$(tag)'
        containerAppName: 'sigil-api'
        resourceGroup: 'reshapelab'
        containerAppEnvironment: 'Production'
        targetPort: '80'
        environmentVariables: 'OPENAI_API_KEY=$(OpenAI-API-Key) MYSQL_HOST=$(MySQL-Host) MYSQL_DATABASE=$(MySQL-DBName-Production) MYSQL_USER=$(MySQL-User) MYSQL_PASSWORD=$(MySQL-Password)'