trigger:
  branches:
    include:
      - feat-*

pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildAndPush
    displayName: Build and Push
    pool:
      name: local
    steps:
    - task: Docker@2
      inputs:
        repository: 'sigil-api'
        containerRegistry: 'SIGIL-PS ACR'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

- stage: Test
  displayName: Deploy Test
  condition: succeeded()
  jobs:
  - deployment: DeployTestContainerApp
    environment: 'Test'
    displayName: Deploy to Test Container App
    pool:
      name: local
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'Azure for Students Subscription'
              KeyVaultName: 'reshapelab-sigil-ps'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: 'Azure for Students Subscription'
              acrName: 'reshapelab'
              acrUsername: 'reshapelab'
              acrPassword: '$(ACR-Password)'
              imageToDeploy: 'reshapelab.azurecr.io/sigil-api:$(tag)'
              containerAppName: 'sigil-api-test'
              resourceGroup: 'reshapelab'
              containerAppEnvironment: 'Test'
              targetPort: '80'
              environmentVariables: 'OPENAI_API_KEY=$(OpenAI-API-Key-Test) MYSQL_HOST=$(MySQL-Host) MYSQL_DATABASE=$(MySQL-DBName-Test) MYSQL_USER=$(MySQL-User) MYSQL_PASSWORD=$(MySQL-Password) MAX_HISTORY=10'

- stage: Production
  displayName: Deploy Production
  condition: succeeded()
  jobs:
  - deployment: DeployProdContainerApp
    environment: 'Production'
    displayName: Deploy to Prod Container App
    pool:
      name: local
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'Azure for Students Subscription'
              KeyVaultName: 'reshapelab-sigil-ps'
              SecretsFilter: '*'
              RunAsPreJob: true
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: 'Azure for Students Subscription'
              acrName: 'reshapelab'
              acrUsername: 'reshapelab'
              acrPassword: '$(ACR-Password)'
              imageToDeploy: 'reshapelab.azurecr.io/sigil-api:$(tag)'
              containerAppName: 'sigil-api'
              resourceGroup: 'reshapelab'
              containerAppEnvironment: 'Test'
              targetPort: '80'
              environmentVariables: 'OPENAI_API_KEY=$(OpenAI-API-Key) MYSQL_HOST=$(MySQL-Host) MYSQL_DATABASE=$(MySQL-DBName-Production) MYSQL_USER=$(MySQL-User) MYSQL_PASSWORD=$(MySQL-Password) MAX_HISTORY=10'