version: "3.9"

services:
  # --- API: DEV ---
  api:
    container_name: sigil-ps-api-dev
    build:
      context: .
    volumes:
      - ./api:/app/api
    ports:
      - "80:80"
    env_file:
      - api/.env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    profiles: ["dev"]
    networks:
      - appnet
    restart: always
    depends_on:
      - db

  # --- API: PROD ---
  api-prod:
    container_name: sigil-ps-api-prod
    build:
      context: .
    ports:
      - "80:80"
    env_file:
      - api/.env
    environment:
      - FLASK_ENV=production
    profiles: ["prod"]
    command: gunicorn -w 4 -b 0.0.0.0:80 api.main:app
    networks:
      - appnet
    restart: always
    depends_on:
      - db

  # --- Database (shared) ---
  db:
    image: mysql:8.0
    container_name: sigil-ps-mysql
    ports:
      - "3306"
    env_file:
      - api/.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  appnet:
