# IMPORTANT: This setup is for local testing ONLY. Do not use this to deploy
version: "3.9"

services:
  # --- API (test/dev environment) ---
  api:
    container_name: sigil-api-test
    build:
      context: .
    volumes:
      - ./api:/app/api
    ports:
      - "80:80"
    env_file:
      - api/.env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MYSQL_HOST=db
      - MYSQL_DATABASE=sigil_db
      - MYSQL_USER=reshapelab_test
      - MYSQL_PASSWORD=reshapeTest2025!
    networks:
      - appnet
    restart: always
    depends_on:
      - db

  # --- Test Database ---
  db:
    image: mysql:8.0
    container_name: sigil-mysql
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=reshapeRoot2025!
      - MYSQL_DATABASE=sigil_db
      - MYSQL_USER=reshapelab_test
      - MYSQL_PASSWORD=reshapeTest2025!
      - MYSQL_SSL_DISABLED=true
    command: --require_secure_transport=OFF # NEVER DO THIS IN PROD! FOR DEV TESTING PURPOSES ONLY
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  appnet: